name: Manual Run with Inputs

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for the changes'
        required: true
      sed_command:
        description: 'Command to run'
        required: true

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.x"

    - name: Run SED command
      run: |
        echo "Running SED command"
        ${{ github.event.inputs.sed_command }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "${{ github.event.inputs.commit_message }}" || echo "No changes to commit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
